In [19]:
import numpy as np

array1 = np.array([1,2,3])
print('array1 type: ', type(array1))
print('array1 형태: ', array1.shape)

array2 = np.array([[1,2,3], [2,3,4]])
print('array2 type: ', type(array2))
print('array2 형태: ', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type: ', type(array3))
print('array3 형태: ', array3.shape)

array1 type:  <class 'numpy.ndarray'>
array1 형태:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 형태:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 형태:  (1, 3)


In [23]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


ndarry내의 데이터 값은 숫자 값, 문자열 값, 불 값 등 모두 가능. 단 한 개의 ndarray 객체에 서로 다른 타입의 데이터를 넣을 수는 없음. 
객체 내 데이터타입 확인하기 위해 .dtype 사용
만약 리스트 내부에 데이터타입 섞여있으면 array로 변환할 때 데이터 크기가 더 큰 데이터 타입으로 일괄 적용함. 

In [31]:
list1 = [1, 2, 3]
print(type(list1))
array = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

list2 =  [1, 2, 'test']
array2 =  np.array(list2)
print(array2, array2.dtype)
list3 =  [1, 2, 3.0]
array3 =  np.array(list3)
print(array3, array3.d)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
['1' '2' 'test'] <U21
[1. 2. 3.] float64


nparray 내의 데이터타입 변경 - astype() 이용. 대용량데이터의 nparray 만들 때 많은 메모리가 사용되면 이를 절약해야 할 때 이용함.

In [35]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


arange() : array를 range()로 표현함. 0부터 함수인자-1 까지의 값을 순차적으로 nparray의 데이터값으로 변환함. (start값 부여해 다른 수에서부터 시작 가능)  
zeros() : 함수 인자로 튜플 형태의 shape값 입력하면 모든 값을 0으로 채운 해당 shape의 nparray 반환.  
ones() : 함수 인자로 튜플 형태의 shape값 입력하면 모든 값을 1으로 채운 해당 shape의 nparray 반환. -> 두 메소드의 경우 default dtype : float64

In [50]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


reshape() : nparray를 특정 차원 및 크기로 변환함  
-1을 인자로 사용하면 원래의 nparray와 호환되는 새로운 shape로 변환해줌.  
reshape(-1, 1)은 원본 nparray가 어떤 형태라도 2차원이고, 여러 개의 row를 가지되 반드시 한 개의 칼럼을 가진 ndarray로 변환시킴. 해당 내용은 여러개의 array를 stack이나 concat으로 결합할 때 형태를 통일하기 위해 유용하게 사용됨.  
+) ndarray는 tolist() 메서드를 이용해 리스트 자료형으로 변환할 수 있음.

In [54]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3) 


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [57]:
array1= np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape: ', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape: ', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape:  (2, 5)
array3 shape:  (5, 2)


In [66]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3:\n', array3d.tolist())

array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


인덱싱 관련 내용  
1. 특정한 데이터만 추출: 원하는 위치의 인덱스 값을 지정하면 해당 위치로 데이터가 반환됨, 단일 인덱스를 이용해 nparray 내의 데이터값 간단히 수정 가능
2. 슬라이싱: 연속된 인덱스상의 ndarray를 추출함. 시작 인덱스~종료인덱스-1 위치에 있는 데이터의 nparray 반환
3. 팬시 인덱싱: 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray 반환
4. 불린 인덱싱: 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환

In [78]:
array1 = np.arange(start=1, stop=10)
print('array1: ', array1)
value = array1[2]
print('value: ', value)
print(type(value))

array1[0] = 9
array1[1] = 8
print(array1)

#다차원의 nparray에서 단일값 추출하기
#axis 0: row 방향에서의 축, axis 1: column 방향에서의 축
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

array1:  [1 2 3 4 5 6 7 8 9]
value:  3
<class 'numpy.int64'>
[9 8 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [84]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

#2차원에서 슬라이싱하기
array1d = array1
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]:\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:2]:\n', array2d[1:3, 0:2])
print('array2d[1:3, :]:\n', array2d[1:3, :])
print('array2d[:, :]:\n', array2d[:, :])
print('array2d[:2, 1:]:\n', array2d[:2, 1:])
print('array2d[:2, 0]:\n', array2d[:2, 0])

print(array2d[0])
print(array2d[1])
print('array2d[0] shape: ', array2d[0].shape, 'array2d[1] shape', array2d[1].shape)

[1 2 3]
<class 'numpy.ndarray'>
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]:
 [[1 2]
 [4 5]]
array2d[1:3, 0:2]:
 [[4 5]
 [7 8]]
array2d[1:3, :]:
 [[4 5 6]
 [7 8 9]]
array2d[:, :]:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]:
 [[2 3]
 [5 6]]
array2d[:2, 0]:
 [1 4]
[1 2 3]
[4 5 6]
array2d[0] shape:  (3,) array2d[1] shape (3,)


In [86]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] => ', array5.tolist())

array2d[[0, 1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0, 1]] =>  [[1, 2, 3], [4, 5, 6]]


In [96]:
array1d = np.arange(start=1, stop=10)
array3 = array1d[array1d>5]
print('array1d 불린 인덱싱 결과 값: ', array3)

array1d > 5
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array4 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과: ', array4)

array1d 불린 인덱싱 결과 값:  [6 7 8 9]
불린 인덱스로 필터링 결과:  [6 7 8 9]


행렬 정렬 1. np.sort() / 2. ndarray.sort()  
1. 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
2. 원 행렬 자체를 정렬한 형태로 변환, 반환값은 None

In [107]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬: ', org_array)

sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬: ', sort_array1)
print('np.sort() 호출 후 원본 행렬: ', org_array)

sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬: ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬: ', org_array)

#내림차순으로 정렬할 때는 [::-1] 적용
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬: ', sort_array1_desc)

#행렬이 2차원 이상일 경우에는 axis 축 값 설정을 통해 로우 방향, 칼럼 방향으로 정렬 수행할 수 있음
array2d = np.array([[8, 12], [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬 :\n', sort_array2d_axis0)
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬 :\n', sort_array2d_axis1)

원본 행렬:  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬:  [1 3 5 9]
np.sort() 호출 후 원본 행렬:  [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬:  None
org_array.sort() 호출 후 원본 행렬:  [1 3 5 9]
내림차순으로 정렬:  [9 5 3 1]
로우 방향으로 정렬 :
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬 :
 [[ 8 12]
 [ 1  7]]


np.argsort() : 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때, 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환  
  
ndarray는 table, df처럼 메타데이터를 가질 수 없기 때문에 실제 값과 그 값이 뜻하는 메타데이터를 별도의 ndarray로 각각 가져야 함. 이때 시험 성적순으로 학생 이름을 출력하고자 한다면 np.argsort(score_array)를 이용해 반환된 인덱스를 name_array에 팬시 인덱스로 적용해 추출할 수 있음.

In [112]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스: ', sort_indices)
#내림차순으로 정렬 시에 원본 행렬의 인덱스를 구하면 [::-1] 동일하게 사용함

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스:  [1 0 3 2]


행렬 내적(행렬곱) : np.dot()을 이용해 계산

In [114]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9,10], [11,12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


전치행렬: np.transpose()

In [121]:
A = np.array([[1, 2], [3,4]])
transpose_A = np.transpose(A)
print('A의 전치 행렬:\n', transpose_A)

A의 전치 행렬:
 [[1 3]
 [2 4]]
